'use strict';

const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const { dataDir } = require('./db');

const MAX_BYTES = 8 * 1024 * 1024;
const MAX_PER_INSPECTION = 12;
const TYPES = { 'image/jpeg': 'jpg', 'image/png': 'png', 'image/webp': 'webp' };

function photoDir() {
  const dir = path.join(dataDir(), 'photos');
  fs.mkdirSync(dir, { recursive: true });
  return dir;
}

// Checks the file's first bytes, not just the declared type.
function sniff(buf) {
  if (buf.length > 3 && buf[0] === 0xff && buf[1] === 0xd8 && buf[2] === 0xff) return 'image/jpeg';
  if (buf.length > 8 && buf.subarray(0, 8).equals(Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]))) return 'image/png';
  if (buf.length > 12 && buf.subarray(0, 4).toString() === 'RIFF' && buf.subarray(8, 12).toString() === 'WEBP') return 'image/webp';
  return null;
}

function save(db, inspection, buf) {
  const mime = sniff(buf);
  if (!mime) {
    const err = new Error('Fișierul nu este o poză JPG, PNG sau WebP.');
    err.status = 415;
    throw err;
  }
  const count = db.prepare('SELECT COUNT(*) n FROM photos WHERE inspection_id = ?').get(inspection.id).n;
  if (count >= MAX_PER_INSPECTION) {
    const err = new Error(`Cel mult ${MAX_PER_INSPECTION} poze pentru o inspecție.`);
    err.status = 409;
    throw err;
  }
  const file = `${crypto.randomBytes(16).toString('hex')}.${TYPES[mime]}`;
  fs.writeFileSync(path.join(photoDir(), file), buf, { flag: 'wx' });
  const r = db.prepare('INSERT INTO photos (inspection_id, vehicle_id, file, mime, size) VALUES (?, ?, ?, ?, ?)')
    .run(inspection.id, inspection.vehicle_id, file, mime, buf.length);
  return { id: Number(r.lastInsertRowid), mime, size: buf.length };
}

function filePath(photo) {
  // `file` is generated by save(); basename guards against a tampered row.
  return path.join(photoDir(), path.basename(photo.file));
}

function remove(db, photo) {
  db.prepare('DELETE FROM photos WHERE id = ?').run(photo.id);
  fs.rm(filePath(photo), { force: true }, () => {});
}

function listFor(db, inspectionIds) {
  if (!inspectionIds.length) return {};
  const rows = db.prepare(`SELECT id, inspection_id, mime, size, created_at FROM photos
    WHERE inspection_id IN (${inspectionIds.map(() => '?').join(',')}) ORDER BY id`).all(...inspectionIds);
  const out = {};
  for (const r of rows) (out[r.inspection_id] ||= []).push({ id: r.id, url: `/api/photos/${r.id}` });
  return out;
}

module.exports = { MAX_BYTES, save, filePath, remove, listFor, sniff };
